# Generated by Django 5.0.4 on 2024-04-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description_short", models.TextField(max_length=255)),
                ("description_long", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/%Y/%m"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("price_marketing", models.FloatField()),
                ("price_marketing_promotional", models.FloatField(default=0)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("V", "Variável"), ("S", "Simples")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
