# Generated by Django 5.0.4 on 2024-05-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_marketing",
            field=models.FloatField(verbose_name="Preço de Venda"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_marketing_promotional",
            field=models.FloatField(default=0, verbose_name="Preço Promocional"),
        ),
    ]
